postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  min_messages: notice
  password:
  pool: 5
  username: mpelzsherman

development: &development
  <<: *postgresql
  database: renter_portal_development

production: &production
  <<: *postgresql
  database: renter_portal_production

test: &test
  <<: *postgresql
  database: renter_portal_test
